// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/bug/ent/runtime.go

const (
	Version = "v0.10.2-0.20220429094929-9d992c4f41ec"           // Version of ent codegen.
	Sum     = "h1:hlQXx+gj9ID9MEcYCA2YKNQ7TKjneI5bR2wlhHTyAzA=" // Sum of ent codegen.
)
