// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/bug/ent/runtime.go

const (
	Version = "v0.11.3-0.20220915211011-0adfb94c30c7"           // Version of ent codegen.
	Sum     = "h1:oDtt9c8I1B0d2rUO4BreKARnqJYEwDHN88PSp6kSQx0=" // Sum of ent codegen.
)
